import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    // Build output, deps, bundled media, and Wrangler's generated Workers
    // types (~15k lines, regenerated by `wrangler types`).
    ignores: [
      "dist/**",
      ".pages/**",
      ".pages-project/**",
      ".local/**",
      "node_modules/**",
      "public/**",
      "worker/env.d.ts",
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  // `shared/` is the layer that ports to Cloudflare unchanged (see
  // docs/architecture.md), so it is given neither Node nor DOM globals. Once
  // worker/ lands, `npm run check:worker` enforces the same boundary through
  // the compiler via "types": []; this keeps the rule visible on main too.
  {
    files: ["shared/**/*.ts"],
    languageOptions: { globals: {} },
    rules: {
      // Same sanitiser rationale as server/ below: shared/library.ts strips
      // \x00-\x1f\x7f from provenance labels before they are rendered.
      "no-control-regex": "off",
    },
  },

  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks },
    rules: {
      // The classic pair. react-hooks v7 also ships the React Compiler rules
      // (refs / set-state-in-effect / purity); they flag 11 idiomatic spots
      // here, so they are a deliberate follow-up rather than a merge blocker.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  {
    files: [
      "server/**/*.ts",
      "worker/**/*.ts",
      "observability/**/*.{ts,mjs}",
      "scripts/**/*.mjs",
      "tests/**/*.{ts,tsx}",
      "*.config.{ts,js}",
    ],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
    rules: {
      // Control-character classes here are the sanitisers, not an accident:
      // filenames, provenance labels and the BFL key are stripped of
      // \x00-\x1f\x7f before use. Flagging them inverts the intent.
      "no-control-regex": "off",
    },
  },

  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
);
